# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_H_cpp <- function(X, M, y, delta, W, H, alpha, lambdaH, eps = 1e-12) {
    invisible(.Call('_DeSurv_update_H_cpp', PACKAGE = 'DeSurv', X, M, y, delta, W, H, alpha, lambdaH, eps))
}

#' @export
calc_loss_cpp <- function(X, M, delta, W, H, beta, alpha, lambda, nu, lambdaW, lambdaH, sdZ) {
    .Call('_DeSurv_calc_loss_cpp', PACKAGE = 'DeSurv', X, M, delta, W, H, beta, alpha, lambda, nu, lambdaW, lambdaH, sdZ)
}

update_beta_cpp <- function(Z, delta, alpha, nu, lambda, beta0, meanZ, sdZ, it, flag_nan, flag_beta, max_bt = 6L, tau_init = 1.0) {
    .Call('_DeSurv_update_beta_cpp', PACKAGE = 'DeSurv', Z, delta, alpha, nu, lambda, beta0, meanZ, sdZ, it, flag_nan, flag_beta, max_bt, tau_init)
}

#' @export
optimize_loss_cpp <- function(X_in, M_in, y_in, delta_in, W0, H0, beta0, alpha, lambda, nu, lambdaW, lambdaH, tol, maxit, verbose, init) {
    .Call('_DeSurv_optimize_loss_cpp', PACKAGE = 'DeSurv', X_in, M_in, y_in, delta_in, W0, H0, beta0, alpha, lambda, nu, lambdaW, lambdaH, tol, maxit, verbose, init)
}

