# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_H_cpp <- function(X, y, delta, W, H, n, p, k, Xnorm, alpha, lambdaH) {
    invisible(.Call(`_DeSurv_update_H_cpp`, X, y, delta, W, H, n, p, k, Xnorm, alpha, lambdaH))
}

calc_loss_cpp <- function(X, y, delta, W, H, beta, n, p, k, n_event, Xnorm, alpha, lambda, nu, lambdaW, lambdaH, sdZ) {
    .Call(`_DeSurv_calc_loss_cpp`, X, y, delta, W, H, beta, n, p, k, n_event, Xnorm, alpha, lambda, nu, lambdaW, lambdaH, sdZ)
}

update_beta_cpp <- function(Z, y, delta, n, p, n_event, alpha, nu, lambda, beta0, meanZ, sdZ, eps, max_iter, flag_nan, flag_beta) {
    .Call(`_DeSurv_update_beta_cpp`, Z, y, delta, n, p, n_event, alpha, nu, lambda, beta0, meanZ, sdZ, eps, max_iter, flag_nan, flag_beta)
}

optimize_loss_cpp <- function(X_in, y_in, delta_in, k, n, p, n_event, W0, H0, beta0, alpha, lambda, nu, lambdaW, lambdaH, tol, maxit, verbose, theta_init, rho, max_backtracks, eps_beta, max_iter_beta, max_iter_beta_final) {
    .Call(`_DeSurv_optimize_loss_cpp`, X_in, y_in, delta_in, k, n, p, n_event, W0, H0, beta0, alpha, lambda, nu, lambdaW, lambdaH, tol, maxit, verbose, theta_init, rho, max_backtracks, eps_beta, max_iter_beta, max_iter_beta_final)
}

